FRsūtil̲s: frsutils.core.models.itfrs.ITFRS Class Reference
frsutils.core.models.itfrs.ITFRS Class Reference
Public Member Functions
__init__ (self, np.ndarray similarity_matrix, np.ndarray labels, tnorms.TNorm tnorm, implicator)
lower_approximation (self)
upper_approximation (self)
Public Member Functions inherited from frsutils.core.approximations.FuzzyRoughModel
__init__ (self, np.ndarray similarity_matrix, np.ndarray labels)
boundary_region (self)
positive_region (self)
Data Fields
tnorm = tnorm
implicator = np.vectorize(implicator)
Data Fields inherited from frsutils.core.approximations.FuzzyRoughModel
similarity_matrix = similarity_matrix
labels = labels
Detailed Description
Definition at line 17 of file itfrs.py.
Constructor & Destructor Documentation
__init__()
frsutils.core.models.itfrs.ITFRS.__init__ (self, np.ndarray similarity_matrix, np.ndarray labels, tnorms.TNorm tnorm, implicator)
Definition at line 18 of file itfrs.py.
    def __init__(self, similarity_matrix: np.ndarray, labels: np.ndarray, tnorm: tnorms.TNorm, implicator):
        super().__init__(similarity_matrix, labels)
        self.tnorm = tnorm
        self.implicator = np.vectorize(implicator)
References __init__().
Referenced by __init__().
Member Function Documentation
lower_approximation()
frsutils.core.models.itfrs.ITFRS.lower_approximation (self)
Reimplemented from frsutils.core.approximations.FuzzyRoughModel.
Definition at line 23 of file itfrs.py.
    def lower_approximation(self):
        label_mask = (self.labels[:, None] == self.labels[None, :]).astype(float)
        implication_vals = self.implicator(self.similarity_matrix, label_mask)
        # Since for the calculations of lower approximation,
        # we calculate Inf which is basically a minimum,
        # to exclude the same instance from calculations we don’t
        #  need anything because the diagonal is set to 1.0 which
        #  is ignored by min operator. To be sure all is correct,
        #  inside code, we set main diagonal to 1.0
        np.fill_diagonal(implication_vals, 1.0)
        return np.min(implication_vals, axis=1)
References implicator, frsutils.core.approximations.FuzzyRoughModel.labels, and frsutils.core.approximations.FuzzyRoughModel.similarity_matrix.
upper_approximation()
frsutils.core.models.itfrs.ITFRS.upper_approximation (self)
Reimplemented from frsutils.core.approximations.FuzzyRoughModel.
Definition at line 36 of file itfrs.py.
    def upper_approximation(self):
        label_mask = (self.labels[:, None] == self.labels[None, :]).astype(float)
        tnorm_vals = self.tnorm(self.similarity_matrix, label_mask)
        # Since for the calculations of upper approximation,
        # we calculate sup which is basically a maximum,
        # to exclude the same instance from calculations we
        # need to set the main diagonal to 0.0 which is ignored
        # by max operator.  Otherwise all upper approxamations will be 1.0.
        np.fill_diagonal(tnorm_vals, 0.0)
        return np.max(tnorm_vals, axis=1)
References frsutils.core.approximations.FuzzyRoughModel.labels, frsutils.core.approximations.FuzzyRoughModel.similarity_matrix, and tnorm.
Field Documentation
implicator
frsutils.core.models.itfrs.ITFRS.implicator = np.vectorize(implicator)
Definition at line 21 of file itfrs.py.
Referenced by lower_approximation(), frsutils.core.models.owafrs.OWAFRS.lower_approximation(), and frsutils.core.models.owafrs.OWAFRS.upper_approximation().
tnorm
frsutils.core.models.itfrs.ITFRS.tnorm = tnorm
Definition at line 20 of file itfrs.py.
Referenced by upper_approximation().
The documentation for this class was generated from the following file:
core/models/itfrs.py